### ISSUE TITLE
wasmer command-line and wasmer-crystal function call results don't match on F32

### ISSUE THREAD

**Issue by jadonk** [naqvis/wasmer-crystal#5]
I am using a simple run.wasm that adds 2 F32 values and returns an F32. When invoked via wasmer-crystal `run.call(11.1, 22.2)`, the return value is bogus, but running `wasmer` from the command-line shows the issue isn't in run.wasm itself.

The spec file for wasmer-crystal seems to show only testing integer values. I'll see if I cannot fix that. 

## run.wasm
```
$ hexdump -C run.wasm 
00000000  00 61 73 6d 01 00 00 00  01 07 01 60 02 7d 7d 01  |.asm.......`.}}.|
00000010  7d 03 02 01 00 07 07 01  03 72 75 6e 00 00 0a 09  |}........run....|
00000020  01 07 00 20 00 20 01 92  0b                       |... . ...|
00000029

$ wasm2wat run.wasm 
(module
  (type (;0;) (func (param f32 f32) (result f32)))
  (func (;0;) (type 0) (param f32 f32) (result f32)
    local.get 0
    local.get 1
    f32.add)
  (export "run" (func 0)))
```

## result of run.call(11.1, 22.2)
```
     Failure/Error: run.call(11.1, 22.2).should eq 33.3

       Expected: 33.3
            got: 8.34465e-8
```

## execution of wasmer from the command-line
```
$ wasmer run.wasm --invoke run 11.1 22.2
33.300003
```

**Comment by naqvis** [comment]
You need to be explicit when using Float32, because Crystal defaults to Float64.

so invoking 
```crystal
run.call(11.1,22.2)
```
will deduce the parameter types as Float64. So to let Crystal knows that you are working with Float32 instead

```crystal
run.call(11.1_f32, 22.2_F32)
```

As you are not providing any typing information, so `11.1` and `22.2` are deduced as `Float64`,  so invoking a wasmer function which expects F32 with F64 params is going to generate garbage values.
